// Se repiten mensajes
export const messages = [
    "🎉 ¡Felicitaciones! Has alcanzado un hito en tu estudio.",
    "🎉 ¡Excelente! Ya llevas varias horas.",
    "🎉 ¡Imparable! Vas camino al éxito.",
    "🎉 ¡No pares! Eres el mejor.",
    "🚀 ¡Cada minuto cuenta, sigue así!",
    "💡 Tu constancia te está llevando lejos.",
    "🔥 ¡Estás encendido! No aflojes ahora.",
    "🌟 Hoy estudias, mañana triunfas.",
    "💪 ¡Tú puedes con todo!",
    "📚 El conocimiento que sumas hoy, será tu fuerza mañana.",
    "✨ Paso a paso, te estás convirtiendo en un maestro.",
    "🏆 El éxito está más cerca de lo que crees.",
    "🎉 ¡Felicitaciones! Has alcanzado un hito en tu estudio.",
    "🎉 ¡Excelente! Ya llevas varias horas.",
    "🎉 ¡Imparable! Vas camino al éxito.",
    "🎉 ¡No pares! Eres el mejor.",
    "🚀 ¡Cada minuto cuenta, sigue así!",
    "💡 Tu constancia te está llevando lejos.",
    "🔥 ¡Estás encendido! No aflojes ahora.",
    "🌟 Hoy estudias, mañana triunfas.",
    "💪 ¡Tú puedes con todo!",
    "📚 El conocimiento que sumas hoy, será tu fuerza mañana.",
    "✨ Paso a paso, te estás convirtiendo en un maestro.",
    "🏆 El éxito está más cerca de lo que crees.",
    "🎉 ¡Felicitaciones! Has alcanzado un hito en tu estudio.",
    "🎉 ¡Excelente! Ya llevas varias horas.",
    "🎉 ¡Imparable! Vas camino al éxito.",
    "🎉 ¡No pares! Eres el mejor.",
    "🚀 ¡Cada minuto cuenta, sigue así!",
    "💡 Tu constancia te está llevando lejos.",
    "🔥 ¡Estás encendido! No aflojes ahora.",
    "🌟 Hoy estudias, mañana triunfas.",
    "💪 ¡Tú puedes con todo!",
    "📚 El conocimiento que sumas hoy, será tu fuerza mañana.",
    "✨ Paso a paso, te estás convirtiendo en un maestro.",
    "🏆 El éxito está más cerca de lo que crees.",
    "🎉 ¡Felicitaciones! Has alcanzado un hito en tu estudio.",
    "🎉 ¡Excelente! Ya llevas varias horas.",
    "🎉 ¡Imparable! Vas camino al éxito.",
    "🎉 ¡No pares! Eres el mejor.",
    "🚀 ¡Cada minuto cuenta, sigue así!",
    "💡 Tu constancia te está llevando lejos.",
    "🔥 ¡Estás encendido! No aflojes ahora.",
    "🌟 Hoy estudias, mañana triunfas.",
    "💪 ¡Tú puedes con todo!",
    "📚 El conocimiento que sumas hoy, será tu fuerza mañana.",
    "✨ Paso a paso, te estás convirtiendo en un maestro.",
    "🏆 El éxito está más cerca de lo que crees.",
    "🎉 ¡Felicitaciones! Has alcanzado un hito en tu estudio.",
    "🎉 ¡Excelente! Ya llevas varias horas.",
    "🎉 ¡Imparable! Vas camino al éxito.",
    "🎉 ¡No pares! Eres el mejor.",
    "🚀 ¡Cada minuto cuenta, sigue así!",
    "💡 Tu constancia te está llevando lejos.",
    "🔥 ¡Estás encendido! No aflojes ahora.",
    "🌟 Hoy estudias, mañana triunfas.",
    "💪 ¡Tú puedes con todo!",
    "📚 El conocimiento que sumas hoy, será tu fuerza mañana.",
    "✨ Paso a paso, te estás convirtiendo en un maestro.",
    "🏆 El éxito está más cerca de lo que crees.",
];